In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np
from sklearn.datasets import load_digits
digits=load_digits()

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.2)

In [18]:
lr=LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

c:\Users\prave\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9666666666666667

In [19]:
rf=RandomForestClassifier()
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.975

In [20]:
svm=SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.9833333333333333

In [21]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=4)
kf

KFold(n_splits=4, random_state=None, shuffle=False)

In [22]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 5 6 7 8] [3 4]
[0 1 2 3 4 7 8] [5 6]
[0 1 2 3 4 5 6] [7 8]


In [23]:
def score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [24]:
score(LogisticRegression(),x_train,x_test,y_train,y_test)

c:\Users\prave\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9666666666666667

In [27]:
from sklearn.model_selection import StratifiedKFold 
folds=StratifiedKFold(n_splits=3)
score_l=[]
score_svm=[]
score_rf=[]

In [33]:
for train_index,test_index in kf.split(digits.data):
    x_train,x_test,y_train,y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    model=LogisticRegression(max_iter=1000)
    score_l.append(score(model,x_train,x_test,y_train,y_test))
    print(score_l)

[0.9355555555555556, 0.9153674832962138, 0.9510022271714922, 0.9175946547884187, 0.9333333333333333, 0.9198218262806236, 0.9487750556792873, 0.9153674832962138, 0.9333333333333333, 0.9198218262806236, 0.9487750556792873, 0.9153674832962138, 0.9333333333333333]
[0.9355555555555556, 0.9153674832962138, 0.9510022271714922, 0.9175946547884187, 0.9333333333333333, 0.9198218262806236, 0.9487750556792873, 0.9153674832962138, 0.9333333333333333, 0.9198218262806236, 0.9487750556792873, 0.9153674832962138, 0.9333333333333333, 0.9198218262806236]
[0.9355555555555556, 0.9153674832962138, 0.9510022271714922, 0.9175946547884187, 0.9333333333333333, 0.9198218262806236, 0.9487750556792873, 0.9153674832962138, 0.9333333333333333, 0.9198218262806236, 0.9487750556792873, 0.9153674832962138, 0.9333333333333333, 0.9198218262806236, 0.9487750556792873]
[0.9355555555555556, 0.9153674832962138, 0.9510022271714922, 0.9175946547884187, 0.9333333333333333, 0.9198218262806236, 0.9487750556792873, 0.91536748329621